### ISSUE TITLE
Limited sources 

### ISSUE THREAD

**Issue by Milkbone18** [jewbmx/repo#47] opened 2024-05-28 13:48 UTC
Good day using  Kodi 20 Nexus latest Verision have had fresh installs of Kodi and add-on but keep getting failed to play errors on almost everything I try to watch.  This on not just one but two of my three firesticks with or without VPN.  I have tried all fixes that have been suggested and no change last night I spend three hours to get the command line in to the new folder and it helped with brand-new movies such a wonka , and Godzilla vs Kong but over all still having the same issues with movies and shows that works two weeks ago one movie my daughter watches religiously will no longer play as of three days ago .so please any help would be greatly appreciated .

**Comment by jewbmx** [comment] 2024-06-20 19:28
Your problems probably gonna be fixed in the next update and the issue is normal not special ;)

**Closed as completed by jewbmx** 2024-06-20 19:28 UTC

**Comment by Milkbone18** [comment] 2024-06-20 19:30
Thank you.  gGeatly appreciate all your hard work you definitely have a great skill.  I hope you're doing well .
